
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "@/components/layout/header";
import { NotificationProvider } from "@/context/NotificationProvider"; // Importe o provedor

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NotificationProvider> {/* Adicione o provedor aqui */}
            <Header />
            {children}
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
